USE [fs]
GO
/****** Object:  Table [dbo].[Directory]    Script Date: 14.01.2023 22:17:46 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Directory](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](100) NOT NULL,
	[ParentId] [int] NULL,
	[IconId] [int] NULL,
 CONSTRAINT [PK_Directory] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Extension]    Script Date: 14.01.2023 22:17:46 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Extension](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[IconId] [int] NULL,
	[Name] [varchar](50) NOT NULL,
 CONSTRAINT [PK_Extension] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[File]    Script Date: 14.01.2023 22:17:46 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[File](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](100) NOT NULL,
	[ExtensionId] [int] NOT NULL,
	[ParentId] [int] NOT NULL,
 CONSTRAINT [PK_File] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Icon]    Script Date: 14.01.2023 22:17:46 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Icon](
	[Id] [int] IDENTITY(4,1) NOT NULL,
	[Data] [varbinary](max) NOT NULL,
 CONSTRAINT [PK_Icon] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[Directory]  WITH CHECK ADD  CONSTRAINT [FK_Directory_Directory] FOREIGN KEY([ParentId])
REFERENCES [dbo].[Directory] ([Id])
GO
ALTER TABLE [dbo].[Directory] CHECK CONSTRAINT [FK_Directory_Directory]
GO
ALTER TABLE [dbo].[Directory]  WITH CHECK ADD  CONSTRAINT [FK_Directory_Icon] FOREIGN KEY([IconId])
REFERENCES [dbo].[Icon] ([Id])
GO
ALTER TABLE [dbo].[Directory] CHECK CONSTRAINT [FK_Directory_Icon]
GO
ALTER TABLE [dbo].[Extension]  WITH CHECK ADD  CONSTRAINT [FK_Extension_Icon] FOREIGN KEY([IconId])
REFERENCES [dbo].[Icon] ([Id])
GO
ALTER TABLE [dbo].[Extension] CHECK CONSTRAINT [FK_Extension_Icon]
GO
ALTER TABLE [dbo].[File]  WITH CHECK ADD  CONSTRAINT [FK_File_Directory] FOREIGN KEY([ParentId])
REFERENCES [dbo].[Directory] ([Id])
GO
ALTER TABLE [dbo].[File] CHECK CONSTRAINT [FK_File_Directory]
GO
ALTER TABLE [dbo].[File]  WITH CHECK ADD  CONSTRAINT [FK_File_Extension] FOREIGN KEY([ExtensionId])
REFERENCES [dbo].[Extension] ([Id])
GO
ALTER TABLE [dbo].[File] CHECK CONSTRAINT [FK_File_Extension]
GO
