//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleCMD.Resources.Connection
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FileSystemEntities : DbContext
    {
        public FileSystemEntities()
            : base("name=FileSystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Directory> Directories { get; set; }
        public virtual DbSet<Extension> Extensions { get; set; }
        public virtual DbSet<File> Files { get; set; }
        public virtual DbSet<Icon> Icons { get; set; }
    }
}
