//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleCMD.Resources.Connection
{
    using System;
    using System.Collections.Generic;
    
    public partial class File
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Extension { get; set; }
        public int Parent { get; set; }
        public Nullable<int> Icon_id { get; set; }
    
        public virtual Directory Directory { get; set; }
        public virtual Icon Icon { get; set; }
    }
}
